name: OfflineStore
version: '1.7'
main: com.jellypudding.offlineStore.OfflineStore
api-version: '1.21'
description: A small shop plugin for MinecraftOffline
author: AlphaAlex115
website: www.minecraftoffline.net
depend: [SimpleVote, ChromaTag, SimpleLifesteal]

commands:
  shop:
    description: Access the shop and buy hearts, name colours, and custom MOTD messages with tokens.
    usage: /shop <category> <action> [value] (for example /shop colour list)
    permission: offlinestore.use
  rules:
    description: Display the server rules.
    usage: /rules
    permission: offlinestore.use
  help:
    description: Display helpful information about server commands and features.
    usage: /help
    permission: offlinestore.use
  kill:
    description: Kill yourself.
    usage: /kill
    permission: offlinestore.use

permissions:
  offlinestore.use:
    description: Allows using the shop.
    default: true
