name: OfflineStore
version: '1.0-SNAPSHOT'
main: com.jellypudding.offlineStore.OfflineStore
api-version: '1.21'
description: A small shop plugin for MinecraftOffline
author: AlphaAlex115
depend: [SimpleVote, ChromaTag]

commands:
  shop:
    description: Opens the shop or manages categories like colours.
    usage: /shop <category> <action> [value] (e.g., /shop colour list)
    permission: offlinestore.use

permissions:
  offlinestore.use:
    description: Allows using the shop.
    default: true
